// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/admin" | "/admin/login" | "/admin/orders" | "/admin/orders/[id]" | "/admin/products" | "/admin/reviews" | "/admin/settings" | "/admin/users" | "/cart" | "/checkout" | "/forgot-password" | "/loading-demo" | "/login" | "/orders" | "/orders/[id]" | "/orders/[id]/review/[productId]" | "/orders/confirmation/[id]" | "/orders/payment/esewa/failure" | "/orders/payment/esewa/success" | "/products" | "/products/[slug]" | "/register" | "/reset-password" | "/verify" | "/verify-email" | "/verify/[reviewId]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/admin": {}
  "/admin/login": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/products": {}
  "/admin/reviews": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/cart": {}
  "/checkout": {}
  "/forgot-password": {}
  "/loading-demo": {}
  "/login": {}
  "/orders": {}
  "/orders/[id]": { "id": string; }
  "/orders/[id]/review/[productId]": { "id": string; "productId": string; }
  "/orders/confirmation/[id]": { "id": string; }
  "/orders/payment/esewa/failure": {}
  "/orders/payment/esewa/success": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/register": {}
  "/reset-password": {}
  "/verify": {}
  "/verify-email": {}
  "/verify/[reviewId]": { "reviewId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
